/**
 * Copyright (C) 2009 - 2010 by OpenGamma Inc.
 *
 * Please see distribution for license.
 */
package com.opengamma.master.position;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import org.joda.beans.BeanDefinition;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaProperty;

import com.opengamma.id.UniqueIdentifier;
import com.opengamma.master.AbstractDocument;
import com.opengamma.util.ArgumentChecker;

/**
 * A document used to pass into and out of the position master.
 */
@BeanDefinition
public class PositionDocument extends AbstractDocument {

  /**
   * The position unique identifier.
   */
  @PropertyDefinition
  private UniqueIdentifier _uniqueId;
  /**
   * The portfolio object identifier.
   */
  @PropertyDefinition
  private UniqueIdentifier _portfolioId;
  /**
   * The parent node object identifier.
   */
  @PropertyDefinition
  private UniqueIdentifier _parentNodeId;
  /**
   * The position.
   */
  @PropertyDefinition
  private ManageablePosition _position;

  /**
   * Creates an instance.
   */
  public PositionDocument() {
  }

  /**
   * Creates an instance from a position.
   * @param position  the position, not null
   */
  public PositionDocument(final ManageablePosition position) {
    ArgumentChecker.notNull(position, "position");
    setUniqueId(position.getUniqueIdentifier());
    setPosition(position);
  }

  /**
   * Creates an instance from a position and parent node id.
   * @param position  the position, not null
   * @param parentNodeId  the parent node identifier, not null
   */
  public PositionDocument(final ManageablePosition position, final UniqueIdentifier parentNodeId) {
    ArgumentChecker.notNull(position, "position");
    ArgumentChecker.notNull(parentNodeId, "parentNodeId");
    setUniqueId(position.getUniqueIdentifier());
    setPosition(position);
    setParentNodeId(parentNodeId);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code PositionDocument}.
   * @return the meta-bean, not null
   */
  public static PositionDocument.Meta meta() {
    return PositionDocument.Meta.INSTANCE;
  }

  @Override
  public PositionDocument.Meta metaBean() {
    return PositionDocument.Meta.INSTANCE;
  }

  @Override
  protected Object propertyGet(String propertyName) {
    switch (propertyName.hashCode()) {
      case -294460212:  // uniqueId
        return getUniqueId();
      case -5186429:  // portfolioId
        return getPortfolioId();
      case 915246087:  // parentNodeId
        return getParentNodeId();
      case 747804969:  // position
        return getPosition();
    }
    return super.propertyGet(propertyName);
  }

  @Override
  protected void propertySet(String propertyName, Object newValue) {
    switch (propertyName.hashCode()) {
      case -294460212:  // uniqueId
        setUniqueId((UniqueIdentifier) newValue);
        return;
      case -5186429:  // portfolioId
        setPortfolioId((UniqueIdentifier) newValue);
        return;
      case 915246087:  // parentNodeId
        setParentNodeId((UniqueIdentifier) newValue);
        return;
      case 747804969:  // position
        setPosition((ManageablePosition) newValue);
        return;
    }
    super.propertySet(propertyName, newValue);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the position unique identifier.
   * @return the value of the property
   */
  public UniqueIdentifier getUniqueId() {
    return _uniqueId;
  }

  /**
   * Sets the position unique identifier.
   * @param uniqueId  the new value of the property
   */
  public void setUniqueId(UniqueIdentifier uniqueId) {
    this._uniqueId = uniqueId;
  }

  /**
   * Gets the the {@code uniqueId} property.
   * @return the property, not null
   */
  public final Property<UniqueIdentifier> uniqueId() {
    return metaBean().uniqueId().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the portfolio object identifier.
   * @return the value of the property
   */
  public UniqueIdentifier getPortfolioId() {
    return _portfolioId;
  }

  /**
   * Sets the portfolio object identifier.
   * @param portfolioId  the new value of the property
   */
  public void setPortfolioId(UniqueIdentifier portfolioId) {
    this._portfolioId = portfolioId;
  }

  /**
   * Gets the the {@code portfolioId} property.
   * @return the property, not null
   */
  public final Property<UniqueIdentifier> portfolioId() {
    return metaBean().portfolioId().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the parent node object identifier.
   * @return the value of the property
   */
  public UniqueIdentifier getParentNodeId() {
    return _parentNodeId;
  }

  /**
   * Sets the parent node object identifier.
   * @param parentNodeId  the new value of the property
   */
  public void setParentNodeId(UniqueIdentifier parentNodeId) {
    this._parentNodeId = parentNodeId;
  }

  /**
   * Gets the the {@code parentNodeId} property.
   * @return the property, not null
   */
  public final Property<UniqueIdentifier> parentNodeId() {
    return metaBean().parentNodeId().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the position.
   * @return the value of the property
   */
  public ManageablePosition getPosition() {
    return _position;
  }

  /**
   * Sets the position.
   * @param position  the new value of the property
   */
  public void setPosition(ManageablePosition position) {
    this._position = position;
  }

  /**
   * Gets the the {@code position} property.
   * @return the property, not null
   */
  public final Property<ManageablePosition> position() {
    return metaBean().position().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code PositionDocument}.
   */
  public static class Meta extends AbstractDocument.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code uniqueId} property.
     */
    private final MetaProperty<UniqueIdentifier> _uniqueId = DirectMetaProperty.ofReadWrite(this, "uniqueId", UniqueIdentifier.class);
    /**
     * The meta-property for the {@code portfolioId} property.
     */
    private final MetaProperty<UniqueIdentifier> _portfolioId = DirectMetaProperty.ofReadWrite(this, "portfolioId", UniqueIdentifier.class);
    /**
     * The meta-property for the {@code parentNodeId} property.
     */
    private final MetaProperty<UniqueIdentifier> _parentNodeId = DirectMetaProperty.ofReadWrite(this, "parentNodeId", UniqueIdentifier.class);
    /**
     * The meta-property for the {@code position} property.
     */
    private final MetaProperty<ManageablePosition> _position = DirectMetaProperty.ofReadWrite(this, "position", ManageablePosition.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<Object>> _map;

    @SuppressWarnings({"unchecked", "rawtypes" })
    protected Meta() {
      LinkedHashMap temp = new LinkedHashMap(super.metaPropertyMap());
      temp.put("uniqueId", _uniqueId);
      temp.put("portfolioId", _portfolioId);
      temp.put("parentNodeId", _parentNodeId);
      temp.put("position", _position);
      _map = Collections.unmodifiableMap(temp);
    }

    @Override
    public PositionDocument createBean() {
      return new PositionDocument();
    }

    @Override
    public Class<? extends PositionDocument> beanType() {
      return PositionDocument.class;
    }

    @Override
    public Map<String, MetaProperty<Object>> metaPropertyMap() {
      return _map;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code uniqueId} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<UniqueIdentifier> uniqueId() {
      return _uniqueId;
    }

    /**
     * The meta-property for the {@code portfolioId} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<UniqueIdentifier> portfolioId() {
      return _portfolioId;
    }

    /**
     * The meta-property for the {@code parentNodeId} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<UniqueIdentifier> parentNodeId() {
      return _parentNodeId;
    }

    /**
     * The meta-property for the {@code position} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<ManageablePosition> position() {
      return _position;
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
