"buy":"${security.buy?string}",
"protectionBuyer":"${security.protectionBuyer.scheme} - ${security.protectionBuyer.value}",
"protectionSeller":"${security.protectionSeller.scheme} - ${security.protectionSeller.value}",
"referenceEntity":"${security.referenceEntity.scheme} - ${security.referenceEntity.value}",
"debtSeniority":"${security.debtSeniority}",
"restructuringClause":"${security.restructuringClause}",
"startDate": "${security.startDate.toLocalDate()}",
"effectiveDate": "${security.effectiveDate.toLocalDate()}",
"maturityDate": "${security.maturityDate.toLocalDate()}",
"stubType":"${security.stubType}",
"couponFrequency":"${security.couponFrequency.conventionName}",
"dayCount":"${security.dayCount.conventionName}",
"businessDayConvention":"${security.businessDayConvention.conventionName}",
"immAdjustMaturityDate":"${security.immAdjustMaturityDate?string}",
"adjustEffectiveDate":"${security.adjustEffectiveDate?string}",
"adjustMaturityDate":"${security.adjustMaturityDate?string}",
"notional":{"amount":"${security.notional.amount}","currency":"${security.notional.currency}"},
"recoveryRate":"${security.recoveryRate}",
"includeAccruedPremium":"${security.includeAccruedPremium?string}",
"protectionStart":"${security.protectionStart?string}",