/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.sesame.component;

import java.util.LinkedHashMap;
import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.component.ComponentRepository;
import com.opengamma.component.factory.AbstractComponentFactory;
import com.opengamma.sesame.engine.DefaultScenarioRunner;
import com.opengamma.sesame.engine.Engine;
import com.opengamma.sesame.engine.ScenarioRunner;

/**
 * Factory for creating and publishing an instance of {@link ScenarioRunner}.
 */
@BeanDefinition
public class ScenarioRunnerComponentFactory extends AbstractComponentFactory {

  /** The classifier that the factory should publish under. */
  @PropertyDefinition(validate = "notEmpty")
  private String _classifier;

  @PropertyDefinition(validate = "notNull")
  private Engine _engine;

  @Override
  public void init(ComponentRepository repo, LinkedHashMap<String, String> configuration) throws Exception {
    repo.registerComponent(ScenarioRunner.class, _classifier, new DefaultScenarioRunner(_engine));
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code ScenarioRunnerComponentFactory}.
   * @return the meta-bean, not null
   */
  public static ScenarioRunnerComponentFactory.Meta meta() {
    return ScenarioRunnerComponentFactory.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(ScenarioRunnerComponentFactory.Meta.INSTANCE);
  }

  @Override
  public ScenarioRunnerComponentFactory.Meta metaBean() {
    return ScenarioRunnerComponentFactory.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the classifier that the factory should publish under.
   * @return the value of the property, not empty
   */
  public String getClassifier() {
    return _classifier;
  }

  /**
   * Sets the classifier that the factory should publish under.
   * @param classifier  the new value of the property, not empty
   */
  public void setClassifier(String classifier) {
    JodaBeanUtils.notEmpty(classifier, "classifier");
    this._classifier = classifier;
  }

  /**
   * Gets the the {@code classifier} property.
   * @return the property, not null
   */
  public final Property<String> classifier() {
    return metaBean().classifier().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the engine.
   * @return the value of the property, not null
   */
  public Engine getEngine() {
    return _engine;
  }

  /**
   * Sets the engine.
   * @param engine  the new value of the property, not null
   */
  public void setEngine(Engine engine) {
    JodaBeanUtils.notNull(engine, "engine");
    this._engine = engine;
  }

  /**
   * Gets the the {@code engine} property.
   * @return the property, not null
   */
  public final Property<Engine> engine() {
    return metaBean().engine().createProperty(this);
  }

  //-----------------------------------------------------------------------
  @Override
  public ScenarioRunnerComponentFactory clone() {
    return JodaBeanUtils.cloneAlways(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      ScenarioRunnerComponentFactory other = (ScenarioRunnerComponentFactory) obj;
      return JodaBeanUtils.equal(getClassifier(), other.getClassifier()) &&
          JodaBeanUtils.equal(getEngine(), other.getEngine()) &&
          super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    hash += hash * 31 + JodaBeanUtils.hashCode(getClassifier());
    hash += hash * 31 + JodaBeanUtils.hashCode(getEngine());
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(96);
    buf.append("ScenarioRunnerComponentFactory{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(StringBuilder buf) {
    super.toString(buf);
    buf.append("classifier").append('=').append(JodaBeanUtils.toString(getClassifier())).append(',').append(' ');
    buf.append("engine").append('=').append(JodaBeanUtils.toString(getEngine())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code ScenarioRunnerComponentFactory}.
   */
  public static class Meta extends AbstractComponentFactory.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code classifier} property.
     */
    private final MetaProperty<String> _classifier = DirectMetaProperty.ofReadWrite(
        this, "classifier", ScenarioRunnerComponentFactory.class, String.class);
    /**
     * The meta-property for the {@code engine} property.
     */
    private final MetaProperty<Engine> _engine = DirectMetaProperty.ofReadWrite(
        this, "engine", ScenarioRunnerComponentFactory.class, Engine.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap(),
        "classifier",
        "engine");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -281470431:  // classifier
          return _classifier;
        case -1298662846:  // engine
          return _engine;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends ScenarioRunnerComponentFactory> builder() {
      return new DirectBeanBuilder<ScenarioRunnerComponentFactory>(new ScenarioRunnerComponentFactory());
    }

    @Override
    public Class<? extends ScenarioRunnerComponentFactory> beanType() {
      return ScenarioRunnerComponentFactory.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code classifier} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<String> classifier() {
      return _classifier;
    }

    /**
     * The meta-property for the {@code engine} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Engine> engine() {
      return _engine;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -281470431:  // classifier
          return ((ScenarioRunnerComponentFactory) bean).getClassifier();
        case -1298662846:  // engine
          return ((ScenarioRunnerComponentFactory) bean).getEngine();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -281470431:  // classifier
          ((ScenarioRunnerComponentFactory) bean).setClassifier((String) newValue);
          return;
        case -1298662846:  // engine
          ((ScenarioRunnerComponentFactory) bean).setEngine((Engine) newValue);
          return;
      }
      super.propertySet(bean, propertyName, newValue, quiet);
    }

    @Override
    protected void validate(Bean bean) {
      JodaBeanUtils.notEmpty(((ScenarioRunnerComponentFactory) bean)._classifier, "classifier");
      JodaBeanUtils.notNull(((ScenarioRunnerComponentFactory) bean)._engine, "engine");
      super.validate(bean);
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
