/**
 * Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.integration.marketdata.manipulator.dsl;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableConstructor;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.threeten.bp.Period;

import com.opengamma.analytics.financial.model.interestrate.curve.YieldAndDiscountCurve;

/**
 * Applies a bucketed shift to a {@link YieldAndDiscountCurve}
 */
@BeanDefinition
public final class YieldCurveBucketedShift implements ImmutableBean {
  
  /**
   * Period between the valuation date and the start of the shift
   */
  @PropertyDefinition(validate = "notNull")
  private final Period _start;
  /**
   * Period between the valuation date and the end of the shift
   */
  @PropertyDefinition(validate = "notNull")
  private final Period _end;
  /**
   * Shift magnitude
   */
  @PropertyDefinition
  private final double _shift;

  @ImmutableConstructor
  public YieldCurveBucketedShift(Period start, Period end, double shift) {
    JodaBeanUtils.notNull(start, "start");
    JodaBeanUtils.notNull(end, "end");
    _start = start;
    _end = end;
    _shift = shift;
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code YieldCurveBucketedShift}.
   * @return the meta-bean, not null
   */
  public static YieldCurveBucketedShift.Meta meta() {
    return YieldCurveBucketedShift.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(YieldCurveBucketedShift.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static YieldCurveBucketedShift.Builder builder() {
    return new YieldCurveBucketedShift.Builder();
  }

  @Override
  public YieldCurveBucketedShift.Meta metaBean() {
    return YieldCurveBucketedShift.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets period between the valuation date and the start of the shift
   * @return the value of the property, not null
   */
  public Period getStart() {
    return _start;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets period between the valuation date and the end of the shift
   * @return the value of the property, not null
   */
  public Period getEnd() {
    return _end;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets shift magnitude
   * @return the value of the property
   */
  public double getShift() {
    return _shift;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      YieldCurveBucketedShift other = (YieldCurveBucketedShift) obj;
      return JodaBeanUtils.equal(getStart(), other.getStart()) &&
          JodaBeanUtils.equal(getEnd(), other.getEnd()) &&
          JodaBeanUtils.equal(getShift(), other.getShift());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getStart());
    hash += hash * 31 + JodaBeanUtils.hashCode(getEnd());
    hash += hash * 31 + JodaBeanUtils.hashCode(getShift());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(128);
    buf.append("YieldCurveBucketedShift{");
    buf.append("start").append('=').append(getStart()).append(',').append(' ');
    buf.append("end").append('=').append(getEnd()).append(',').append(' ');
    buf.append("shift").append('=').append(JodaBeanUtils.toString(getShift()));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code YieldCurveBucketedShift}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code start} property.
     */
    private final MetaProperty<Period> _start = DirectMetaProperty.ofImmutable(
        this, "start", YieldCurveBucketedShift.class, Period.class);
    /**
     * The meta-property for the {@code end} property.
     */
    private final MetaProperty<Period> _end = DirectMetaProperty.ofImmutable(
        this, "end", YieldCurveBucketedShift.class, Period.class);
    /**
     * The meta-property for the {@code shift} property.
     */
    private final MetaProperty<Double> _shift = DirectMetaProperty.ofImmutable(
        this, "shift", YieldCurveBucketedShift.class, Double.TYPE);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "start",
        "end",
        "shift");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 109757538:  // start
          return _start;
        case 100571:  // end
          return _end;
        case 109407362:  // shift
          return _shift;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public YieldCurveBucketedShift.Builder builder() {
      return new YieldCurveBucketedShift.Builder();
    }

    @Override
    public Class<? extends YieldCurveBucketedShift> beanType() {
      return YieldCurveBucketedShift.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code start} property.
     * @return the meta-property, not null
     */
    public MetaProperty<Period> start() {
      return _start;
    }

    /**
     * The meta-property for the {@code end} property.
     * @return the meta-property, not null
     */
    public MetaProperty<Period> end() {
      return _end;
    }

    /**
     * The meta-property for the {@code shift} property.
     * @return the meta-property, not null
     */
    public MetaProperty<Double> shift() {
      return _shift;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 109757538:  // start
          return ((YieldCurveBucketedShift) bean).getStart();
        case 100571:  // end
          return ((YieldCurveBucketedShift) bean).getEnd();
        case 109407362:  // shift
          return ((YieldCurveBucketedShift) bean).getShift();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code YieldCurveBucketedShift}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<YieldCurveBucketedShift> {

    private Period _start;
    private Period _end;
    private double _shift;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(YieldCurveBucketedShift beanToCopy) {
      this._start = beanToCopy.getStart();
      this._end = beanToCopy.getEnd();
      this._shift = beanToCopy.getShift();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 109757538:  // start
          return _start;
        case 100571:  // end
          return _end;
        case 109407362:  // shift
          return _shift;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 109757538:  // start
          this._start = (Period) newValue;
          break;
        case 100571:  // end
          this._end = (Period) newValue;
          break;
        case 109407362:  // shift
          this._shift = (Double) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public YieldCurveBucketedShift build() {
      return new YieldCurveBucketedShift(
          _start,
          _end,
          _shift);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code start} property in the builder.
     * @param start  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder start(Period start) {
      JodaBeanUtils.notNull(start, "start");
      this._start = start;
      return this;
    }

    /**
     * Sets the {@code end} property in the builder.
     * @param end  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder end(Period end) {
      JodaBeanUtils.notNull(end, "end");
      this._end = end;
      return this;
    }

    /**
     * Sets the {@code shift} property in the builder.
     * @param shift  the new value
     * @return this, for chaining, not null
     */
    public Builder shift(double shift) {
      this._shift = shift;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(128);
      buf.append("YieldCurveBucketedShift.Builder{");
      buf.append("start").append('=').append(JodaBeanUtils.toString(_start)).append(',').append(' ');
      buf.append("end").append('=').append(JodaBeanUtils.toString(_end)).append(',').append(' ');
      buf.append("shift").append('=').append(JodaBeanUtils.toString(_shift));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
