/**
 * Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.financial.analytics.curve;

import java.util.Collections;
import java.util.Map;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.analytics.financial.legalentity.LegalEntity;
import com.opengamma.analytics.financial.legalentity.LegalEntityCombiningFilter;
import com.opengamma.analytics.financial.legalentity.LegalEntityFilter;
import com.opengamma.analytics.financial.legalentity.LegalEntityShortName;
import com.opengamma.util.ArgumentChecker;

/**
 * Configuration object for curves that are to be used as an issuer curve.
 * This class should no longer be used directly, as it contains unnecessary
 * information about the underlying reference. Equivalent functionality is
 * found in {@link IssuerShortNameCurveTypeConfiguration}.
 */
@BeanDefinition
public class IssuerCurveTypeConfiguration extends CurveTypeConfiguration {

  /** Serialization version */
  private static final long serialVersionUID = 1L;

  /**
   * The issuer name.
   */
  @PropertyDefinition(validate = "notNull")
  private LegalEntityCombiningFilter _filters;

  /**
   * The underlying reference.
   * @deprecated This field is no longer used.
   */
  @Deprecated
  @PropertyDefinition(validate = "notNull")
  private String _underlyingReference;

  /**
   * For the fudge builder
   */
  /* package */ IssuerCurveTypeConfiguration() {
    super();
  }

  /**
   * @param issuerName The issuer name, not null
   * @param underlyingReference The underlying reference (e.g. a currency) for the curve
   * @deprecated This configuration no longer uses the underlyingReference field.
   */
  @Deprecated
  public IssuerCurveTypeConfiguration(final String issuerName, final String underlyingReference) {
    super();
    final LegalEntityCombiningFilter filters =
        new LegalEntityCombiningFilter(Collections.<LegalEntityFilter<LegalEntity>>singleton(new LegalEntityShortName()));
    setFilters(filters);
  }

  /**
   * @param filters The legal entity filters, not null
   */
  public IssuerCurveTypeConfiguration(final Set<LegalEntityFilter<LegalEntity>> filters) {
    super();
    ArgumentChecker.notNull(filters, "filters");
    setFilters(new LegalEntityCombiningFilter(filters));
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code IssuerCurveTypeConfiguration}.
   * @return the meta-bean, not null
   */
  public static IssuerCurveTypeConfiguration.Meta meta() {
    return IssuerCurveTypeConfiguration.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(IssuerCurveTypeConfiguration.Meta.INSTANCE);
  }

  @Override
  public IssuerCurveTypeConfiguration.Meta metaBean() {
    return IssuerCurveTypeConfiguration.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the issuer name.
   * @return the value of the property, not null
   */
  public LegalEntityCombiningFilter getFilters() {
    return _filters;
  }

  /**
   * Sets the issuer name.
   * @param filters  the new value of the property, not null
   */
  public void setFilters(final LegalEntityCombiningFilter filters) {
    JodaBeanUtils.notNull(filters, "filters");
    this._filters = filters;
  }

  /**
   * Gets the the {@code filters} property.
   * @return the property, not null
   */
  public final Property<LegalEntityCombiningFilter> filters() {
    return metaBean().filters().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the underlying reference.
   * @deprecated This field is no longer used.
   * @return the value of the property, not null
   */
  @Deprecated
  public String getUnderlyingReference() {
    return _underlyingReference;
  }

  /**
   * Sets the underlying reference.
   * @deprecated This field is no longer used.
   * @param underlyingReference  the new value of the property, not null
   */
  @Deprecated
  public void setUnderlyingReference(final String underlyingReference) {
    JodaBeanUtils.notNull(underlyingReference, "underlyingReference");
    this._underlyingReference = underlyingReference;
  }

  /**
   * Gets the the {@code underlyingReference} property.
   * @deprecated This field is no longer used.
   * @return the property, not null
   */
  @Deprecated
  public final Property<String> underlyingReference() {
    return metaBean().underlyingReference().createProperty(this);
  }

  //-----------------------------------------------------------------------
  @Override
  public IssuerCurveTypeConfiguration clone() {
    return (IssuerCurveTypeConfiguration) super.clone();
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      final IssuerCurveTypeConfiguration other = (IssuerCurveTypeConfiguration) obj;
      return JodaBeanUtils.equal(getFilters(), other.getFilters()) &&
          JodaBeanUtils.equal(getUnderlyingReference(), other.getUnderlyingReference()) &&
          super.equals(obj);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = 7;
    hash += hash * 31 + JodaBeanUtils.hashCode(getFilters());
    hash += hash * 31 + JodaBeanUtils.hashCode(getUnderlyingReference());
    return hash ^ super.hashCode();
  }

  @Override
  public String toString() {
    final StringBuilder buf = new StringBuilder(96);
    buf.append("IssuerCurveTypeConfiguration{");
    final int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  @Override
  protected void toString(final StringBuilder buf) {
    super.toString(buf);
    buf.append("filters").append('=').append(JodaBeanUtils.toString(getFilters())).append(',').append(' ');
    buf.append("underlyingReference").append('=').append(JodaBeanUtils.toString(getUnderlyingReference())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code IssuerCurveTypeConfiguration}.
   */
  public static class Meta extends CurveTypeConfiguration.Meta {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code filters} property.
     */
    private final MetaProperty<LegalEntityCombiningFilter> _filters = DirectMetaProperty.ofReadWrite(
        this, "filters", IssuerCurveTypeConfiguration.class, LegalEntityCombiningFilter.class);
    /**
     * The meta-property for the {@code underlyingReference} property.
     */
    private final MetaProperty<String> _underlyingReference = DirectMetaProperty.ofReadWrite(
        this, "underlyingReference", IssuerCurveTypeConfiguration.class, String.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, (DirectMetaPropertyMap) super.metaPropertyMap(),
        "filters",
        "underlyingReference");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(final String propertyName) {
      switch (propertyName.hashCode()) {
        case -854547461:  // filters
          return _filters;
        case -1415245714:  // underlyingReference
          return _underlyingReference;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends IssuerCurveTypeConfiguration> builder() {
      return new DirectBeanBuilder<IssuerCurveTypeConfiguration>(new IssuerCurveTypeConfiguration());
    }

    @Override
    public Class<? extends IssuerCurveTypeConfiguration> beanType() {
      return IssuerCurveTypeConfiguration.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code filters} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LegalEntityCombiningFilter> filters() {
      return _filters;
    }

    /**
     * The meta-property for the {@code underlyingReference} property.
     * @deprecated This field is no longer used.
     * @return the meta-property, not null
     */
    @Deprecated
    public final MetaProperty<String> underlyingReference() {
      return _underlyingReference;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(final Bean bean, final String propertyName, final boolean quiet) {
      switch (propertyName.hashCode()) {
        case -854547461:  // filters
          return ((IssuerCurveTypeConfiguration) bean).getFilters();
        case -1415245714:  // underlyingReference
          return ((IssuerCurveTypeConfiguration) bean).getUnderlyingReference();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(final Bean bean, final String propertyName, final Object newValue, final boolean quiet) {
      switch (propertyName.hashCode()) {
        case -854547461:  // filters
          ((IssuerCurveTypeConfiguration) bean).setFilters((LegalEntityCombiningFilter) newValue);
          return;
        case -1415245714:  // underlyingReference
          ((IssuerCurveTypeConfiguration) bean).setUnderlyingReference((String) newValue);
          return;
      }
      super.propertySet(bean, propertyName, newValue, quiet);
    }

    @Override
    protected void validate(final Bean bean) {
      JodaBeanUtils.notNull(((IssuerCurveTypeConfiguration) bean)._filters, "filters");
      JodaBeanUtils.notNull(((IssuerCurveTypeConfiguration) bean)._underlyingReference, "underlyingReference");
      super.validate(bean);
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
