/**
 * Copyright (C) 2009 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.component;

import java.util.Map;

import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

/**
 * Stores information about the published components.
 * <p>
 * Components are defined in terms of an interface type.
 */
@BeanDefinition
public class PublishedComponent extends DirectBean {

  /**
   * The instance that is to be managed by {@code DataComponentsResource}.
   */
  @PropertyDefinition(validate = "notNull")
  private Object _instance;
  /**
   * The component info for the instance.
   */
  @PropertyDefinition(validate = "notNull")
  private ComponentInfo _info;

  /**
   * Creates an instance.
   */
  protected PublishedComponent() {
  }

  /**
   * Creates an instance.
   * 
   * @param info  the managed component info, not null
   * @param instance  the managed component instance, not null
   */
  public PublishedComponent(ComponentInfo info, Object instance) {
    setInfo(info);
    setInstance(instance);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code PublishedComponent}.
   * @return the meta-bean, not null
   */
  public static PublishedComponent.Meta meta() {
    return PublishedComponent.Meta.INSTANCE;
  }
  static {
    JodaBeanUtils.registerMetaBean(PublishedComponent.Meta.INSTANCE);
  }

  @Override
  public PublishedComponent.Meta metaBean() {
    return PublishedComponent.Meta.INSTANCE;
  }

  @Override
  protected Object propertyGet(String propertyName, boolean quiet) {
    switch (propertyName.hashCode()) {
      case 555127957:  // instance
        return getInstance();
      case 3237038:  // info
        return getInfo();
    }
    return super.propertyGet(propertyName, quiet);
  }

  @Override
  protected void propertySet(String propertyName, Object newValue, boolean quiet) {
    switch (propertyName.hashCode()) {
      case 555127957:  // instance
        setInstance((Object) newValue);
        return;
      case 3237038:  // info
        setInfo((ComponentInfo) newValue);
        return;
    }
    super.propertySet(propertyName, newValue, quiet);
  }

  @Override
  protected void validate() {
    JodaBeanUtils.notNull(_instance, "instance");
    JodaBeanUtils.notNull(_info, "info");
    super.validate();
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      PublishedComponent other = (PublishedComponent) obj;
      return JodaBeanUtils.equal(getInstance(), other.getInstance()) &&
          JodaBeanUtils.equal(getInfo(), other.getInfo());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getInstance());
    hash += hash * 31 + JodaBeanUtils.hashCode(getInfo());
    return hash;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the instance that is to be managed by {@code DataComponentsResource}.
   * @return the value of the property, not null
   */
  public Object getInstance() {
    return _instance;
  }

  /**
   * Sets the instance that is to be managed by {@code DataComponentsResource}.
   * @param instance  the new value of the property, not null
   */
  public void setInstance(Object instance) {
    JodaBeanUtils.notNull(instance, "instance");
    this._instance = instance;
  }

  /**
   * Gets the the {@code instance} property.
   * @return the property, not null
   */
  public final Property<Object> instance() {
    return metaBean().instance().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the component info for the instance.
   * @return the value of the property, not null
   */
  public ComponentInfo getInfo() {
    return _info;
  }

  /**
   * Sets the component info for the instance.
   * @param info  the new value of the property, not null
   */
  public void setInfo(ComponentInfo info) {
    JodaBeanUtils.notNull(info, "info");
    this._info = info;
  }

  /**
   * Gets the the {@code info} property.
   * @return the property, not null
   */
  public final Property<ComponentInfo> info() {
    return metaBean().info().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code PublishedComponent}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code instance} property.
     */
    private final MetaProperty<Object> _instance = DirectMetaProperty.ofReadWrite(
        this, "instance", PublishedComponent.class, Object.class);
    /**
     * The meta-property for the {@code info} property.
     */
    private final MetaProperty<ComponentInfo> _info = DirectMetaProperty.ofReadWrite(
        this, "info", PublishedComponent.class, ComponentInfo.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<Object>> _map = new DirectMetaPropertyMap(
        this, null,
        "instance",
        "info");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 555127957:  // instance
          return _instance;
        case 3237038:  // info
          return _info;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends PublishedComponent> builder() {
      return new DirectBeanBuilder<PublishedComponent>(new PublishedComponent());
    }

    @Override
    public Class<? extends PublishedComponent> beanType() {
      return PublishedComponent.class;
    }

    @Override
    public Map<String, MetaProperty<Object>> metaPropertyMap() {
      return _map;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code instance} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Object> instance() {
      return _instance;
    }

    /**
     * The meta-property for the {@code info} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<ComponentInfo> info() {
      return _info;
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
