/**
 * Copyright (C) 2012 - present by OpenGamma Inc. and the OpenGamma group of companies
 * 
 * Please see distribution for license.
 */
package com.opengamma.core.user.impl;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.Sets;
import com.opengamma.core.user.OGEntitlement;
import com.opengamma.core.user.OGRole;
import com.opengamma.id.MutableUniqueIdentifiable;
import com.opengamma.id.UniqueId;

/**
 * Simple implementation of {@code OGRole}.
 * <p>
 * This is the simplest possible implementation of the {@link com.opengamma.core.user.OGRole} interface.
 * <p>
 * This class is mutable and not thread-safe.
 * It is intended to be used in the engine via the read-only {@code OGRole} interface.
 */
@BeanDefinition
public class SimpleOGRole extends DirectBean implements OGRole, MutableUniqueIdentifiable, Serializable {

  /** Serialization version. */
  private static final long serialVersionUID = 1L;

  /**
   * The unique identifier of the role.
   */
  @PropertyDefinition
  private UniqueId _uniqueId;

  /**
   * The role key, used to create capabilities that role is entitled to.
   */
  @PropertyDefinition(validate = "notNull")
  private String _key;

  /**
   * The entitlements for the role.
   * This is a set of entitlements that the role has, which enables access restriction.
   */
  @PropertyDefinition(validate = "notNull")
  private final Set<OGEntitlement> _entitlements = Sets.newHashSet();
  /**
   * The display role name, used to identify the role in a GUI.
   */
  @PropertyDefinition
  private String _name;


  /**
   * Creates a role.
   */
  protected SimpleOGRole() {
  }

  /**
   * Creates a role.
   *
   * @param name the role name, not null
   */
  public SimpleOGRole(String name) {
    _name = name;
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code SimpleOGRole}.
   * @return the meta-bean, not null
   */
  public static SimpleOGRole.Meta meta() {
    return SimpleOGRole.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(SimpleOGRole.Meta.INSTANCE);
  }

  @Override
  public SimpleOGRole.Meta metaBean() {
    return SimpleOGRole.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the unique identifier of the role.
   * @return the value of the property
   */
  public UniqueId getUniqueId() {
    return _uniqueId;
  }

  /**
   * Sets the unique identifier of the role.
   * @param uniqueId  the new value of the property
   */
  public void setUniqueId(UniqueId uniqueId) {
    this._uniqueId = uniqueId;
  }

  /**
   * Gets the the {@code uniqueId} property.
   * @return the property, not null
   */
  public final Property<UniqueId> uniqueId() {
    return metaBean().uniqueId().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the role key, used to create capabilities that role is entitled to.
   * @return the value of the property, not null
   */
  public String getKey() {
    return _key;
  }

  /**
   * Sets the role key, used to create capabilities that role is entitled to.
   * @param key  the new value of the property, not null
   */
  public void setKey(String key) {
    JodaBeanUtils.notNull(key, "key");
    this._key = key;
  }

  /**
   * Gets the the {@code key} property.
   * @return the property, not null
   */
  public final Property<String> key() {
    return metaBean().key().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the entitlements for the role.
   * This is a set of entitlements that the role has, which enables access restriction.
   * @return the value of the property, not null
   */
  public Set<OGEntitlement> getEntitlements() {
    return _entitlements;
  }

  /**
   * Sets the entitlements for the role.
   * This is a set of entitlements that the role has, which enables access restriction.
   * @param entitlements  the new value of the property, not null
   */
  public void setEntitlements(Set<OGEntitlement> entitlements) {
    JodaBeanUtils.notNull(entitlements, "entitlements");
    this._entitlements.clear();
    this._entitlements.addAll(entitlements);
  }

  /**
   * Gets the the {@code entitlements} property.
   * This is a set of entitlements that the role has, which enables access restriction.
   * @return the property, not null
   */
  public final Property<Set<OGEntitlement>> entitlements() {
    return metaBean().entitlements().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the display role name, used to identify the role in a GUI.
   * @return the value of the property
   */
  public String getName() {
    return _name;
  }

  /**
   * Sets the display role name, used to identify the role in a GUI.
   * @param name  the new value of the property
   */
  public void setName(String name) {
    this._name = name;
  }

  /**
   * Gets the the {@code name} property.
   * @return the property, not null
   */
  public final Property<String> name() {
    return metaBean().name().createProperty(this);
  }

  //-----------------------------------------------------------------------
  @Override
  public SimpleOGRole clone() {
    BeanBuilder<? extends SimpleOGRole> builder = metaBean().builder();
    for (MetaProperty<?> mp : metaBean().metaPropertyIterable()) {
      if (mp.style().isBuildable()) {
        Object value = mp.get(this);
        if (value instanceof Bean) {
          value = ((Bean) value).clone();
        }
        builder.set(mp.name(), value);
      }
    }
    return builder.build();
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      SimpleOGRole other = (SimpleOGRole) obj;
      return JodaBeanUtils.equal(getUniqueId(), other.getUniqueId()) &&
          JodaBeanUtils.equal(getKey(), other.getKey()) &&
          JodaBeanUtils.equal(getEntitlements(), other.getEntitlements()) &&
          JodaBeanUtils.equal(getName(), other.getName());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getUniqueId());
    hash += hash * 31 + JodaBeanUtils.hashCode(getKey());
    hash += hash * 31 + JodaBeanUtils.hashCode(getEntitlements());
    hash += hash * 31 + JodaBeanUtils.hashCode(getName());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(160);
    buf.append("SimpleOGRole{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("uniqueId").append('=').append(JodaBeanUtils.toString(getUniqueId())).append(',').append(' ');
    buf.append("key").append('=').append(JodaBeanUtils.toString(getKey())).append(',').append(' ');
    buf.append("entitlements").append('=').append(JodaBeanUtils.toString(getEntitlements())).append(',').append(' ');
    buf.append("name").append('=').append(JodaBeanUtils.toString(getName())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code SimpleOGRole}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code uniqueId} property.
     */
    private final MetaProperty<UniqueId> _uniqueId = DirectMetaProperty.ofReadWrite(
        this, "uniqueId", SimpleOGRole.class, UniqueId.class);
    /**
     * The meta-property for the {@code key} property.
     */
    private final MetaProperty<String> _key = DirectMetaProperty.ofReadWrite(
        this, "key", SimpleOGRole.class, String.class);
    /**
     * The meta-property for the {@code entitlements} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<Set<OGEntitlement>> _entitlements = DirectMetaProperty.ofReadWrite(
        this, "entitlements", SimpleOGRole.class, (Class) Set.class);
    /**
     * The meta-property for the {@code name} property.
     */
    private final MetaProperty<String> _name = DirectMetaProperty.ofReadWrite(
        this, "name", SimpleOGRole.class, String.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "uniqueId",
        "key",
        "entitlements",
        "name");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -294460212:  // uniqueId
          return _uniqueId;
        case 106079:  // key
          return _key;
        case -1704576794:  // entitlements
          return _entitlements;
        case 3373707:  // name
          return _name;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends SimpleOGRole> builder() {
      return new DirectBeanBuilder<SimpleOGRole>(new SimpleOGRole());
    }

    @Override
    public Class<? extends SimpleOGRole> beanType() {
      return SimpleOGRole.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code uniqueId} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<UniqueId> uniqueId() {
      return _uniqueId;
    }

    /**
     * The meta-property for the {@code key} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<String> key() {
      return _key;
    }

    /**
     * The meta-property for the {@code entitlements} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Set<OGEntitlement>> entitlements() {
      return _entitlements;
    }

    /**
     * The meta-property for the {@code name} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<String> name() {
      return _name;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -294460212:  // uniqueId
          return ((SimpleOGRole) bean).getUniqueId();
        case 106079:  // key
          return ((SimpleOGRole) bean).getKey();
        case -1704576794:  // entitlements
          return ((SimpleOGRole) bean).getEntitlements();
        case 3373707:  // name
          return ((SimpleOGRole) bean).getName();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -294460212:  // uniqueId
          ((SimpleOGRole) bean).setUniqueId((UniqueId) newValue);
          return;
        case 106079:  // key
          ((SimpleOGRole) bean).setKey((String) newValue);
          return;
        case -1704576794:  // entitlements
          ((SimpleOGRole) bean).setEntitlements((Set<OGEntitlement>) newValue);
          return;
        case 3373707:  // name
          ((SimpleOGRole) bean).setName((String) newValue);
          return;
      }
      super.propertySet(bean, propertyName, newValue, quiet);
    }

    @Override
    protected void validate(Bean bean) {
      JodaBeanUtils.notNull(((SimpleOGRole) bean)._key, "key");
      JodaBeanUtils.notNull(((SimpleOGRole) bean)._entitlements, "entitlements");
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
