/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.financial.analytics.model.fixedincome;

import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.ImmutableMap;
import com.opengamma.analytics.math.matrix.DoubleMatrix2D;
import com.opengamma.financial.analytics.DoubleLabelledMatrix2D;

/**
 * Cross Sensitivities as a map keyed by curve name and holding the curve sensitivities by {@link DoubleMatrix2D}
 */
@BeanDefinition
public final class BucketedCrossSensitivities implements ImmutableBean {
  
  @PropertyDefinition(validate = "notNull")
  private final Map<String, DoubleLabelledMatrix2D> _crossSensitivities;

  /**
   * Create cross, curve, sensitivities from an input map.
   *
   * @param sensitivities the sensitivities as a map keyed by curve name and holding {@link DoubleMatrix2D}
   * @return the cross sensitivities object
   */
  public static BucketedCrossSensitivities of(Map<String, DoubleLabelledMatrix2D> sensitivities) {
    return builder().crossSensitivities(sensitivities).build();
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code BucketedCrossSensitivities}.
   * @return the meta-bean, not null
   */
  public static BucketedCrossSensitivities.Meta meta() {
    return BucketedCrossSensitivities.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(BucketedCrossSensitivities.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static BucketedCrossSensitivities.Builder builder() {
    return new BucketedCrossSensitivities.Builder();
  }

  private BucketedCrossSensitivities(
      Map<String, DoubleLabelledMatrix2D> crossSensitivities) {
    JodaBeanUtils.notNull(crossSensitivities, "crossSensitivities");
    this._crossSensitivities = ImmutableMap.copyOf(crossSensitivities);
  }

  @Override
  public BucketedCrossSensitivities.Meta metaBean() {
    return BucketedCrossSensitivities.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the crossSensitivities.
   * @return the value of the property, not null
   */
  public Map<String, DoubleLabelledMatrix2D> getCrossSensitivities() {
    return _crossSensitivities;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      BucketedCrossSensitivities other = (BucketedCrossSensitivities) obj;
      return JodaBeanUtils.equal(getCrossSensitivities(), other.getCrossSensitivities());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getCrossSensitivities());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("BucketedCrossSensitivities{");
    buf.append("crossSensitivities").append('=').append(JodaBeanUtils.toString(getCrossSensitivities()));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code BucketedCrossSensitivities}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code crossSensitivities} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<Map<String, DoubleLabelledMatrix2D>> _crossSensitivities = DirectMetaProperty.ofImmutable(
        this, "crossSensitivities", BucketedCrossSensitivities.class, (Class) Map.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "crossSensitivities");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 188138269:  // crossSensitivities
          return _crossSensitivities;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BucketedCrossSensitivities.Builder builder() {
      return new BucketedCrossSensitivities.Builder();
    }

    @Override
    public Class<? extends BucketedCrossSensitivities> beanType() {
      return BucketedCrossSensitivities.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code crossSensitivities} property.
     * @return the meta-property, not null
     */
    public MetaProperty<Map<String, DoubleLabelledMatrix2D>> crossSensitivities() {
      return _crossSensitivities;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 188138269:  // crossSensitivities
          return ((BucketedCrossSensitivities) bean).getCrossSensitivities();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code BucketedCrossSensitivities}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<BucketedCrossSensitivities> {

    private Map<String, DoubleLabelledMatrix2D> _crossSensitivities = new HashMap<String, DoubleLabelledMatrix2D>();

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(BucketedCrossSensitivities beanToCopy) {
      this._crossSensitivities = new HashMap<String, DoubleLabelledMatrix2D>(beanToCopy.getCrossSensitivities());
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 188138269:  // crossSensitivities
          return _crossSensitivities;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @SuppressWarnings("unchecked")
    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 188138269:  // crossSensitivities
          this._crossSensitivities = (Map<String, DoubleLabelledMatrix2D>) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public BucketedCrossSensitivities build() {
      return new BucketedCrossSensitivities(
          _crossSensitivities);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code crossSensitivities} property in the builder.
     * @param crossSensitivities  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder crossSensitivities(Map<String, DoubleLabelledMatrix2D> crossSensitivities) {
      JodaBeanUtils.notNull(crossSensitivities, "crossSensitivities");
      this._crossSensitivities = crossSensitivities;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("BucketedCrossSensitivities.Builder{");
      buf.append("crossSensitivities").append('=').append(JodaBeanUtils.toString(_crossSensitivities));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
