DROP USER opengamma;

CREATE USER opengamma IDENTIFIED BY opengamma
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users
QUOTA UNLIMITED ON temp;

GRANT CONNECT TO opengamma;
GRANT CREATE TABLE TO opengamma;
GRANT CREATE SEQUENCE TO opengamma;