/**
 * Copyright (C) 2012 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.financial.analytics;

/**
 * Function exclusion groups for use with the OG-Analytics package.
 */
public final class OpenGammaFunctionExclusions {

  private OpenGammaFunctionExclusions() {
  }

  //CSOFF
  public static final String BLACK_VOLATILITY_SURFACE_DEFAULTS = "BLACK_VOLATILITY_SURFACE_DEFAULTS";
  public static final String FX_BLACK_VOLATILITY_SURFACE_DEFAULTS = "FX_BLACK_VOLATILITY_SURFACE_DEFAULTS";
  public static final String COMMODITY_BLACK_VOLATILITY_SURFACE_DEFAULTS = "COMMODITY_BLACK_VOLATILITY_SURFACE_DEFAULTS";
  public static final String EQUITY_BLACK_VOLATILITY_SURFACE_DEFAULTS = "EQUITY_BLACK_VOLATILITY_SURFACE_DEFAULTS";
  public static final String EQUITY_PURE_VOLATILITY_SURFACE_DEFAULTS = "EQUITY_PURE_VOLATILITY_SURFACE_DEFAULTS";
  public static final String BLACK_VOLATILITY_SURFACE_INTERPOLATOR_DEFAULTS = "BLACK_VOLATILITY_SURFACE_INTERPOLATOR_DEFAULTS";
  public static final String PDE_DEFAULTS = "PDE_DEFAULTS";
  public static final String PDE_CURVE_DEFAULTS = "PDE_CURVE_DEFAULTS";
  public static final String LOCAL_VOLATILITY_SURFACE_DEFAULTS = "LOCAL_VOLATILITY_SURFACE_DEFAULTS";
  public static final String PNL_SERIES = "PNL_SERIES";
  public static final String INTEREST_RATE_INSTRUMENT_DEFAULTS = "INTEREST_RATE_INSTRUMENT_DEFAULTS";
  public static final String EXTERNALLY_PROVIDED_SENSITIVITIES_DEFAULTS = "EXTERNALLY PROVIDED SENSITIVITIES DEFAULTS";
  public static final String EQUITY_VARIANCE_SWAP_DEFAULTS = "EQUITY VARIANCE SWAP DEFAULTS";
  public static final String EQUITY_FUTURE_DEFAULTS = "EQUITY FUTURE DEFAULTS";
  public static final String EQUITY_OPTION_SURFACE_CALCULATION_METHOD_DEFAULTS = "EQUITY_OPTION_SURFACE_CALCULAION_METHOD_DEFAULTS";
  public static final String EQUITY_OPTION_INTERPOLATED_BLACK_LOGNORMAL_DEFAULTS = "EQUITY_OPTION_INTERPOLATED_BLACK_LOGNORMAL_DEFAULTS";
  public static final String SABR_FITTING_DEFAULTS = "SABR_FITTING_DEFAULTS";
  public static final String FX_FORWARD_DEFAULTS = "FX_FORWARD_DEFAULTS";
  public static final String FX_FORWARD_THETA_DEFAULTS = "FX_FORWARD_THETA_DEFAULTS";
  public static final String FX_OPTION_BLACK_DEFAULTS = "FX_OPTION_BLACK_DEFAULTS";
  public static final String FX_OPTION_BLACK_CURVE_DEFAULTS = "FX_OPTION_BLACK_CURVE_DEFAULTS";
  public static final String FX_OPTION_BLACK_SURFACE_DEFAULTS = "FX_OPTION_BLACK_SURFACE_DEFAULTS";
  public static final String FX_DIGITAL_OPTION_CALL_SPREAD_BLACK_DEFAULTS = "FX_DIGITAL_OPTION_CALL_SPREAD_BLACK_DEFAULTS";
  public static final String FX_OPTION_THETA_DEFAULTS = "FX_OPTION_THETA_DEFAULTS";
  public static final String NORMAL_HISTORICAL_VAR = "NORMAL_HISTORICAL_VAR";
  public static final String EMPIRICAL_HISTORICAL_VAR = "EMPIRICAL_HISTORICAL_VAR";
  public static final String SWAPTION_BLACK_DEFAULTS = "SWAPTION_BLACK_DEFAULTS";
  public static final String INTEREST_RATE_FUTURE = "INTEREST_RATE_FUTURE";
  public static final String FUTURE_OPTION_BLACK = "FUTURE_OPTION_BLACK";
  public static final String ISDA_LEGACY_CDS_CURVE = "ISDA_LEGACY_CDS_CURVE";
  public static final String ISDA_LEGACY_CDS_PRICING = "ISDA_LEGACY_CDS";
  public static final String IMPLIED_FX_FORWARD_CURVE_DEFAULTS = "IMPLIED_FX_FORWARD_CURVE_DEFAULTS";
  public static final String INTEREST_RATE_FUTURE_OPTION_HESTON = "INTEREST_RATE_FUTURE_OPTION_HESTON";
  //CSON



}
