/**
 * Copyright (C) 2012 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.financial.analytics;

/**
 * Function exclusion groups for use with the OG-Analytics package.
 */
public interface OpenGammaFunctionExclusions {

  //CSOFF
  public static final String BLACK_VOLATILITY_SURFACE_DEFAULTS = "BLACK_VOLATILITY_SURFACE_DEFAULTS";
  public static final String SURFACE_DEFAULTS = "SURFACE";
  public static final String EQUITY_PURE_VOLATILITY_SURFACE_DEFAULTS = "EQUITY_PURE_VOLATILITY_SURFACE_DEFAULTS";
  public static final String BLACK_VOLATILITY_SURFACE_INTERPOLATOR_DEFAULTS = "BLACK_VOLATILITY_SURFACE_INTERPOLATOR_DEFAULTS";
  public static final String PDE_DEFAULTS = "PDE_DEFAULTS";
  public static final String CURVE_DEFAULTS = "CURVE";
  public static final String LOCAL_VOLATILITY_SURFACE_DEFAULTS = "LOCAL_VOLATILITY_SURFACE_DEFAULTS";
  public static final String PNL_SERIES = "PNL_SERIES";
  public static final String INTEREST_RATE_INSTRUMENT_DEFAULTS = "INTEREST_RATE_INSTRUMENT_DEFAULTS";
  public static final String EXTERNALLY_PROVIDED_SENSITIVITIES_DEFAULTS = "EXTERNALLY PROVIDED SENSITIVITIES DEFAULTS";
  public static final String EQUITY_VARIANCE_SWAP_DEFAULTS = "EQUITY VARIANCE SWAP DEFAULTS";
  public static final String EQUITY_FUTURE_DEFAULTS = "EQUITY FUTURE DEFAULTS";
  public static final String SURFACE_CALCULATION_METHOD_DEFAULTS = "30SURFACE_CALCULATION_METHOD_DEFAULTS";
  public static final String CALCULATION_METHOD_DEFAULTS = "40CALCULATION_METHOD_DEFAULTS";
  public static final String EQUITY_OPTION_DEFAULTS = "10EQUITY_OPTION_DEFAULTS";
  public static final String INTERPOLATED_BLACK_LOGNORMAL_DEFAULTS = "20INTERPOLATED_BLACK_LOGNORMAL_DEFAULTS";
  public static final String EQUITY_FORWARD_CURVE_DEFAULTS = "EQUITY_FORWARD_CURVE_DEFAULTS";
  public static final String COMMODITY_FORWARD_CURVE_DEFAULTS = "COMMODITY_FORWARD_CURVE_DEFAULTS";
  public static final String SABR_FITTING_DEFAULTS = "SABR_FITTING_DEFAULTS";
  public static final String XCCY_SWAP_DEFAULTS = "XCCY_SWAP_DEFAULTS";
  public static final String FX_FORWARD_DEFAULTS = "FX_FORWARD_DEFAULTS";
  public static final String FX_FORWARD_THETA_DEFAULTS = "FX_FORWARD_THETA_DEFAULTS";
  public static final String FX_OPTION_BLACK_DEFAULTS = "FX_OPTION_BLACK_DEFAULTS";
  public static final String FX_DIGITAL_OPTION_CALL_SPREAD_BLACK_DEFAULTS = "FX_DIGITAL_OPTION_CALL_SPREAD_BLACK_DEFAULTS";
  public static final String FX_OPTION_THETA_DEFAULTS = "FX_OPTION_THETA_DEFAULTS";
  public static final String NORMAL_HISTORICAL_VAR = "NORMAL_HISTORICAL_VAR";
  public static final String EMPIRICAL_HISTORICAL_VAR = "EMPIRICAL_HISTORICAL_VAR";
  public static final String SWAPTION_BASIC_BLACK_DEFAULTS = "SWAPTION_BASIC_BLACK_DEFAULTS";
  public static final String SWAPTION_BLACK_DEFAULTS = "SWAPTION_BLACK_DEFAULTS";
  public static final String INTEREST_RATE_FUTURE = "INTEREST_RATE_FUTURE";
  public static final String FUTURE_OPTION_BLACK = "FUTURE_OPTION_BLACK";
  public static final String ISDA_LEGACY_CDS_CURVE = "ISDA_LEGACY_CDS_CURVE";
  public static final String ISDA_LEGACY_CDS_PRICING = "ISDA_LEGACY_CDS";
  public static final String INTEREST_RATE_FUTURE_OPTION_HESTON = "INTEREST_RATE_FUTURE_OPTION_HESTON";
  public static final String ISDA_COMPLIANT_YIELD_CURVE_DEFAULTS = "ISDA_COMPLIANT_YIELD_CURVE";
  public static final String ISDA_COMPLIANT_CREDIT_CURVE_DEFAULTS = "ISDA_COMPLIANT_CREDIT_CURVE";
  public static final String ISDA_COMPLIANT_HAZARD_CURVE_DEFAULTS = "ISDA_COMPLIANT_HAZARD_CURVE";
  public static final String ISDA_COMPLIANT_IR01 = "ISDA_COMPLIANT_IR01";
  public static final String ISDA_COMPLIANT_CS01 = "ISDA_COMPLIANT_CS01";
  public static final String ISDA_COMPLIANT_RR01 = "ISDA_COMPLIANT_RR01";
  public static final String ISDA_COMPLIANT_PRICE = "ISDA_COMPLIANT_PRICE";

  //CSON

  String getMutualExclusionGroup();

}
