/**
 * Copyright (C) 2009 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.master.batch;

import java.util.Map;

import javax.time.Instant;

import com.opengamma.id.*;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.util.paging.PagingRequest;

/**
 * Request for searching for batches.
 * <p>
 * Documents will be returned that match the search criteria.
 * This class provides the ability to page the results.
 * <p>
 * This class is mutable and not thread-safe.
 */
@BeanDefinition
public class BatchSearchRequest extends DirectBean {

  /**
   * The request for paging.
   * By default all matching items will be returned.
   */
  @PropertyDefinition
  private PagingRequest _pagingRequest = PagingRequest.ALL;

  /**
   * The unique id of the market data snapshot used by the batch
   */
  @PropertyDefinition
  private UniqueId _marketDataSnapshotUid;

  /**
   * The unique id of the view definition used by the batch
   */
  @PropertyDefinition
  private UniqueId _viewDefinitionUid;

  /**
   * The version correction used by the batch
   */
  @PropertyDefinition
  private com.opengamma.id.VersionCorrection _versionCorrection;

  /**
   * The valuation time used by the batch
   */
  @PropertyDefinition
  private Instant _valuationTime;
  
  


  /**
   * Creates an instance.
   */
  public BatchSearchRequest() {
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code BatchSearchRequest}.
   * @return the meta-bean, not null
   */
  public static BatchSearchRequest.Meta meta() {
    return BatchSearchRequest.Meta.INSTANCE;
  }
  static {
    JodaBeanUtils.registerMetaBean(BatchSearchRequest.Meta.INSTANCE);
  }

  @Override
  public BatchSearchRequest.Meta metaBean() {
    return BatchSearchRequest.Meta.INSTANCE;
  }

  @Override
  protected Object propertyGet(String propertyName, boolean quiet) {
    switch (propertyName.hashCode()) {
      case -2092032669:  // pagingRequest
        return getPagingRequest();
      case -1278853626:  // marketDataSnapshotUid
        return getMarketDataSnapshotUid();
      case 276749144:  // viewDefinitionUid
        return getViewDefinitionUid();
      case -2031293866:  // versionCorrection
        return getVersionCorrection();
      case 113591406:  // valuationTime
        return getValuationTime();
    }
    return super.propertyGet(propertyName, quiet);
  }

  @Override
  protected void propertySet(String propertyName, Object newValue, boolean quiet) {
    switch (propertyName.hashCode()) {
      case -2092032669:  // pagingRequest
        setPagingRequest((PagingRequest) newValue);
        return;
      case -1278853626:  // marketDataSnapshotUid
        setMarketDataSnapshotUid((UniqueId) newValue);
        return;
      case 276749144:  // viewDefinitionUid
        setViewDefinitionUid((UniqueId) newValue);
        return;
      case -2031293866:  // versionCorrection
        setVersionCorrection((com.opengamma.id.VersionCorrection) newValue);
        return;
      case 113591406:  // valuationTime
        setValuationTime((Instant) newValue);
        return;
    }
    super.propertySet(propertyName, newValue, quiet);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      BatchSearchRequest other = (BatchSearchRequest) obj;
      return JodaBeanUtils.equal(getPagingRequest(), other.getPagingRequest()) &&
          JodaBeanUtils.equal(getMarketDataSnapshotUid(), other.getMarketDataSnapshotUid()) &&
          JodaBeanUtils.equal(getViewDefinitionUid(), other.getViewDefinitionUid()) &&
          JodaBeanUtils.equal(getVersionCorrection(), other.getVersionCorrection()) &&
          JodaBeanUtils.equal(getValuationTime(), other.getValuationTime());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getPagingRequest());
    hash += hash * 31 + JodaBeanUtils.hashCode(getMarketDataSnapshotUid());
    hash += hash * 31 + JodaBeanUtils.hashCode(getViewDefinitionUid());
    hash += hash * 31 + JodaBeanUtils.hashCode(getVersionCorrection());
    hash += hash * 31 + JodaBeanUtils.hashCode(getValuationTime());
    return hash;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the request for paging.
   * By default all matching items will be returned.
   * @return the value of the property
   */
  public PagingRequest getPagingRequest() {
    return _pagingRequest;
  }

  /**
   * Sets the request for paging.
   * By default all matching items will be returned.
   * @param pagingRequest  the new value of the property
   */
  public void setPagingRequest(PagingRequest pagingRequest) {
    this._pagingRequest = pagingRequest;
  }

  /**
   * Gets the the {@code pagingRequest} property.
   * By default all matching items will be returned.
   * @return the property, not null
   */
  public final Property<PagingRequest> pagingRequest() {
    return metaBean().pagingRequest().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the unique id of the market data snapshot used by the batch
   * @return the value of the property
   */
  public UniqueId getMarketDataSnapshotUid() {
    return _marketDataSnapshotUid;
  }

  /**
   * Sets the unique id of the market data snapshot used by the batch
   * @param marketDataSnapshotUid  the new value of the property
   */
  public void setMarketDataSnapshotUid(UniqueId marketDataSnapshotUid) {
    this._marketDataSnapshotUid = marketDataSnapshotUid;
  }

  /**
   * Gets the the {@code marketDataSnapshotUid} property.
   * @return the property, not null
   */
  public final Property<UniqueId> marketDataSnapshotUid() {
    return metaBean().marketDataSnapshotUid().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the unique id of the view definition used by the batch
   * @return the value of the property
   */
  public UniqueId getViewDefinitionUid() {
    return _viewDefinitionUid;
  }

  /**
   * Sets the unique id of the view definition used by the batch
   * @param viewDefinitionUid  the new value of the property
   */
  public void setViewDefinitionUid(UniqueId viewDefinitionUid) {
    this._viewDefinitionUid = viewDefinitionUid;
  }

  /**
   * Gets the the {@code viewDefinitionUid} property.
   * @return the property, not null
   */
  public final Property<UniqueId> viewDefinitionUid() {
    return metaBean().viewDefinitionUid().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the version correction used by the batch
   * @return the value of the property
   */
  public com.opengamma.id.VersionCorrection getVersionCorrection() {
    return _versionCorrection;
  }

  /**
   * Sets the version correction used by the batch
   * @param versionCorrection  the new value of the property
   */
  public void setVersionCorrection(com.opengamma.id.VersionCorrection versionCorrection) {
    this._versionCorrection = versionCorrection;
  }

  /**
   * Gets the the {@code versionCorrection} property.
   * @return the property, not null
   */
  public final Property<com.opengamma.id.VersionCorrection> versionCorrection() {
    return metaBean().versionCorrection().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the valuation time used by the batch
   * @return the value of the property
   */
  public Instant getValuationTime() {
    return _valuationTime;
  }

  /**
   * Sets the valuation time used by the batch
   * @param valuationTime  the new value of the property
   */
  public void setValuationTime(Instant valuationTime) {
    this._valuationTime = valuationTime;
  }

  /**
   * Gets the the {@code valuationTime} property.
   * @return the property, not null
   */
  public final Property<Instant> valuationTime() {
    return metaBean().valuationTime().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code BatchSearchRequest}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code pagingRequest} property.
     */
    private final MetaProperty<PagingRequest> _pagingRequest = DirectMetaProperty.ofReadWrite(
        this, "pagingRequest", BatchSearchRequest.class, PagingRequest.class);
    /**
     * The meta-property for the {@code marketDataSnapshotUid} property.
     */
    private final MetaProperty<UniqueId> _marketDataSnapshotUid = DirectMetaProperty.ofReadWrite(
        this, "marketDataSnapshotUid", BatchSearchRequest.class, UniqueId.class);
    /**
     * The meta-property for the {@code viewDefinitionUid} property.
     */
    private final MetaProperty<UniqueId> _viewDefinitionUid = DirectMetaProperty.ofReadWrite(
        this, "viewDefinitionUid", BatchSearchRequest.class, UniqueId.class);
    /**
     * The meta-property for the {@code versionCorrection} property.
     */
    private final MetaProperty<com.opengamma.id.VersionCorrection> _versionCorrection = DirectMetaProperty.ofReadWrite(
        this, "versionCorrection", BatchSearchRequest.class, com.opengamma.id.VersionCorrection.class);
    /**
     * The meta-property for the {@code valuationTime} property.
     */
    private final MetaProperty<Instant> _valuationTime = DirectMetaProperty.ofReadWrite(
        this, "valuationTime", BatchSearchRequest.class, Instant.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<Object>> _map = new DirectMetaPropertyMap(
        this, null,
        "pagingRequest",
        "marketDataSnapshotUid",
        "viewDefinitionUid",
        "versionCorrection",
        "valuationTime");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -2092032669:  // pagingRequest
          return _pagingRequest;
        case -1278853626:  // marketDataSnapshotUid
          return _marketDataSnapshotUid;
        case 276749144:  // viewDefinitionUid
          return _viewDefinitionUid;
        case -2031293866:  // versionCorrection
          return _versionCorrection;
        case 113591406:  // valuationTime
          return _valuationTime;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends BatchSearchRequest> builder() {
      return new DirectBeanBuilder<BatchSearchRequest>(new BatchSearchRequest());
    }

    @Override
    public Class<? extends BatchSearchRequest> beanType() {
      return BatchSearchRequest.class;
    }

    @Override
    public Map<String, MetaProperty<Object>> metaPropertyMap() {
      return _map;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code pagingRequest} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<PagingRequest> pagingRequest() {
      return _pagingRequest;
    }

    /**
     * The meta-property for the {@code marketDataSnapshotUid} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<UniqueId> marketDataSnapshotUid() {
      return _marketDataSnapshotUid;
    }

    /**
     * The meta-property for the {@code viewDefinitionUid} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<UniqueId> viewDefinitionUid() {
      return _viewDefinitionUid;
    }

    /**
     * The meta-property for the {@code versionCorrection} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<com.opengamma.id.VersionCorrection> versionCorrection() {
      return _versionCorrection;
    }

    /**
     * The meta-property for the {@code valuationTime} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Instant> valuationTime() {
      return _valuationTime;
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
