CREATE TABLE  sec_equity_variance_swap (
  id bigint not null,
  security_id bigint not null,
  annualization_factor double precision not null,
  currency_id bigint not null,
  first_observation_date timestamp not null,
  first_observation_zone varchar(50) not null,
  last_observation_date timestamp not null,
  last_observation_zone varchar(50) not null,
  notional double precision not null,
  observation_frequency_id bigint not null,
  parameterised_as_variance boolean not null,
  region_scheme varchar(255) not null,
  region_id varchar(255) not null,
  settlement_date timestamp not null,
  settlement_zone varchar(50) not null,
  spot_scheme varchar(255) not null,
  spot_id varchar(255) not null,
  strike double precision not null,
  
  primary key (id),
  constraint sec_fk_equityvarianceswap2sec foreign key (security_id) references sec_security (id),
  constraint sec_fk_equityvarianceswap2currency foreign key (currency_id) references sec_currency(id),
  constraint sec_fk_equityvarianceswap2frequency foreign key (observation_frequency_id) references sec_frequency (id)
);
