/**
 * Copyright (C) 2009 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.financial.currency;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.opengamma.engine.ComputationTarget;
import com.opengamma.engine.ComputationTargetType;
import com.opengamma.engine.function.AbstractFunction;
import com.opengamma.engine.function.FunctionCompilationContext;
import com.opengamma.engine.function.FunctionExecutionContext;
import com.opengamma.engine.function.FunctionInputs;
import com.opengamma.engine.value.ComputedValue;
import com.opengamma.engine.value.ValueProperties;
import com.opengamma.engine.value.ValueRequirement;
import com.opengamma.engine.value.ValueRequirementNames;
import com.opengamma.engine.value.ValueSpecification;
import com.opengamma.financial.OpenGammaCompilationContext;
import com.opengamma.financial.currency.CurrencyMatrixValue.CurrencyMatrixCross;
import com.opengamma.financial.currency.CurrencyMatrixValue.CurrencyMatrixFixed;
import com.opengamma.financial.currency.CurrencyMatrixValue.CurrencyMatrixValueRequirement;
import com.opengamma.id.UniqueId;
import com.opengamma.util.money.Currency;
import com.opengamma.util.timeseries.DoubleTimeSeries;
import com.opengamma.util.tuple.Pair;

/**
 * Injects a value from a {@link CurrencyMatrix} into a dependency graph to satisfy the currency requirements generated by {@link CurrencyConversionFunction}.
 */
public class CurrencyMatrixSourcingFunction extends AbstractFunction.NonCompiledInvoker {

  private static final Logger s_logger = LoggerFactory.getLogger(CurrencyMatrixSourcingFunction.class);

  private static final String CURRENCY_MATRIX_NAME_PROPERTY = "CurrencyMatrix";

  /**
   * Scheme used for the target primitive.
   */
  public static final String TARGET_IDENTIFIER_SCHEME = "CurrencyPair";

  private final String _currencyMatrixName;
  private final String[] _additionalProperties;
  private CurrencyMatrix _currencyMatrix;

  public CurrencyMatrixSourcingFunction(final String currencyMatrixName) {
    _currencyMatrixName = currencyMatrixName;
    _additionalProperties = null;
  }

  public CurrencyMatrixSourcingFunction(final String[] params) {
    _currencyMatrixName = params[0];
    _additionalProperties = new String[params.length - 1];
    System.arraycopy(params, 1, _additionalProperties, 0, _additionalProperties.length);
  }

  @Override
  protected ValueProperties.Builder createValueProperties() {
    final ValueProperties.Builder properties = super.createValueProperties();
    properties.with(CURRENCY_MATRIX_NAME_PROPERTY, _currencyMatrixName);
    if (_additionalProperties != null) {
      for (int i = 0; i < _additionalProperties.length; i += 2) {
        properties.with(_additionalProperties[i], _additionalProperties[i + 1]);
      }
    }
    return properties;
  }

  private static Pair<Currency, Currency> parse(final ComputationTarget target) {
    final String value = target.getUniqueId().getValue();
    if (value.length() != 6) {
      return null;
    }
    try {
      final Currency sourceCurrency = Currency.of(value.substring(0, 3));
      final Currency targetCurrency = Currency.of(value.substring(3, 6));
      return Pair.of(sourceCurrency, targetCurrency);
    } catch (final IllegalArgumentException e) {
      return null;
    }
  }

  protected CurrencyMatrix getCurrencyMatrix() {
    return _currencyMatrix;
  }

  protected void setCurrencyMatrix(final CurrencyMatrix currencyMatrix) {
    _currencyMatrix = currencyMatrix;
  }

  protected String getCurrencyMatrixName() {
    return _currencyMatrixName;
  }

  @Override
  public void init(final FunctionCompilationContext context) {
    final CurrencyMatrix matrix = OpenGammaCompilationContext.getCurrencyMatrixSource(context).getCurrencyMatrix(getCurrencyMatrixName());
    setCurrencyMatrix(matrix);
    if (matrix != null) {
      if (matrix.getUniqueId() != null) {
        context.getFunctionReinitializer().reinitializeFunction(this, matrix.getUniqueId().getObjectId());
      }
    }
  }

  @Override
  public Set<ComputedValue> execute(final FunctionExecutionContext executionContext, final FunctionInputs inputs, final ComputationTarget target, final Set<ValueRequirement> desiredValues) {
    final ValueRequirement desiredValue = desiredValues.iterator().next();
    final Pair<Currency, Currency> currencies = parse(target);
    return Collections.singleton(new ComputedValue(new ValueSpecification(ValueRequirementNames.SPOT_RATE, target.toSpecification(), desiredValue.getConstraints()),
          getConversionRate(inputs, currencies.getFirst(), currencies.getSecond())));
  }

  @Override
  public boolean canApplyTo(final FunctionCompilationContext context, final ComputationTarget target) {
    if (getCurrencyMatrix() == null) {
      return false;
    }
    if (target.getUniqueId() == null) {
      return false;
    }
    if (!TARGET_IDENTIFIER_SCHEME.equals(target.getUniqueId().getScheme())) {
      return false;
    }
    final Pair<Currency, Currency> currencies = parse(target);
    if (currencies == null) {
      return false;
    }
    return getConversionRequirements(currencies) != null;
  }

  private boolean getConversionRequirements(final Set<ValueRequirement> requirements, final Set<Pair<Currency, Currency>> visited, final Pair<Currency, Currency> currencies) {
    if (!visited.add(currencies)) {
      // Gone round in a loop if we've already seen this pair
      throw new IllegalStateException();
    }
    final CurrencyMatrixValue value = getCurrencyMatrix().getConversion(currencies.getFirst(), currencies.getSecond());
    if (value != null) {
      return value.accept(new CurrencyMatrixValueVisitor<Boolean>() {

        @Override
        public Boolean visitCross(final CurrencyMatrixCross cross) {
          return getConversionRequirements(requirements, visited, Pair.of(currencies.getFirst(), cross.getCrossCurrency()))
              && getConversionRequirements(requirements, visited, Pair.of(cross.getCrossCurrency(), currencies.getSecond()));
        }

        @Override
        public Boolean visitFixed(final CurrencyMatrixFixed fixedValue) {
          // Literal value - nothing required
          return Boolean.TRUE;
        }

        @Override
        public Boolean visitValueRequirement(final CurrencyMatrixValueRequirement valueRequirement) {
          requirements.add(valueRequirement.getValueRequirement());
          return Boolean.TRUE;
        }

      });
    } else {
      return false;
    }
  }

  private Set<ValueRequirement> getConversionRequirements(final Pair<Currency, Currency> currencies) {
    if (getCurrencyMatrix() == null) {
      return null;
    }
    final HashSet<ValueRequirement> requirements = new HashSet<ValueRequirement>();
    if (!getConversionRequirements(requirements, new HashSet<Pair<Currency, Currency>>(), currencies)) {
      return null;
    }
    return requirements;
  }

  private Object getConversionRate(final FunctionInputs inputs, final Currency source, final Currency target) {
    final CurrencyMatrixValue value = getCurrencyMatrix().getConversion(source, target);
    final Object rate = value.accept(new CurrencyMatrixValueVisitor<Object>() {

      @Override
      public Object visitCross(final CurrencyMatrixCross cross) {
        final Object r1 = getConversionRate(inputs, source, cross.getCrossCurrency());
        final Object r2 = getConversionRate(inputs, cross.getCrossCurrency(), target);
        if (r1 instanceof Double) {
          if (r2 instanceof Double) {
            return (Double) r1 * (Double) r2;
          } else {
            throw new IllegalArgumentException();
          }
        } else if (r1 instanceof DoubleTimeSeries) {
          if (r2 instanceof DoubleTimeSeries) {
            return ((DoubleTimeSeries<?>) r1).multiply((DoubleTimeSeries<?>) r2);
          } else {
            throw new IllegalArgumentException();
          }
        } else {
          throw new IllegalArgumentException();
        }
      }

      @Override
      public Object visitFixed(final CurrencyMatrixFixed fixedValue) {
        return fixedValue.getFixedValue();
      }

      @Override
      public Object visitValueRequirement(final CurrencyMatrixValueRequirement valueRequirement) {
        final Object marketValue = inputs.getValue(valueRequirement.getValueRequirement());
        if (marketValue instanceof Number) {
          double rate = ((Number) marketValue).doubleValue();
          if (valueRequirement.isReciprocal()) {
            rate = 1.0 / rate;
          }
          return rate;
        } else if (marketValue instanceof DoubleTimeSeries) {
          DoubleTimeSeries<?> rate = (DoubleTimeSeries<?>) marketValue;
          if (valueRequirement.isReciprocal()) {
            rate = rate.reciprocal();
          }
          return rate;
        } else {
          throw new IllegalArgumentException(valueRequirement.toString());
        }
      }

    });
    s_logger.debug("{} to {} = {}", new Object[] {source, target, rate });
    return rate;
  }

  @Override
  public Set<ValueRequirement> getRequirements(final FunctionCompilationContext context, final ComputationTarget target, final ValueRequirement desiredValue) {
    final Pair<Currency, Currency> currencies = parse(target);
    return getConversionRequirements(currencies);
  }

  @Override
  public Set<ValueSpecification> getResults(final FunctionCompilationContext context, final ComputationTarget target) {
    return Collections.singleton(new ValueSpecification(ValueRequirementNames.SPOT_RATE, target.toSpecification(), createValueProperties().get()));
  }

  @Override
  public ComputationTargetType getTargetType() {
    return ComputationTargetType.PRIMITIVE;
  }

  public int getPriority() {
    if (_currencyMatrixName.contains(CurrencyMatrixConfigPopulator.SYNTHETIC_LIVE_DATA)) {
      return -1;
    }
    return 0;
  }

  /**
   * Creates a requirement that will supply a value which gives the number of units of the source currency for each unit of the target currency.
   * 
   * @param source the source currency to convert from
   * @param target the target currency to convert to
   * @return the requirement, not null
   */
  public static ValueRequirement getConversionRequirement(final Currency source, final Currency target) {
    return getConversionRequirement(source.getCode(), target.getCode());
  }

  /**
   * Creates a requirement that will supply a value which gives the number of units of the source currency for each unit of the target currency.
   * 
   * @param source the source currency to convert from
   * @param target the target currency to convert to
   * @return the requirement, not null
   */
  public static ValueRequirement getConversionRequirement(final String source, final String target) {
    return new ValueRequirement(ValueRequirementNames.SPOT_RATE, ComputationTargetType.PRIMITIVE, UniqueId.of(TARGET_IDENTIFIER_SCHEME, source + target));
  }

}
