DROP DATABASE IF EXISTS og_tss;

DROP ROLE IF EXISTS tssowner;

CREATE ROLE tssowner LOGIN
NOSUPERUSER INHERIT CREATEDB CREATEROLE;
COMMENT ON ROLE tssowner IS 'timeseries_storage owner';
ALTER ROLE tssowner WITH PASSWORD 'ajT0xnJj';

DROP ROLE IF EXISTS tssreader;

CREATE ROLE tssreader LOGIN
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
COMMENT ON ROLE tssreader IS 'readonly account for og_tss';
ALTER ROLE tssreader WITH PASSWORD 'ytN3qjEP';

DROP ROLE IF EXISTS tssupdater;

CREATE ROLE tssupdater LOGIN
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
COMMENT ON ROLE tssupdater IS 'update only account for og_tss';
ALTER ROLE tssupdater WITH PASSWORD 'petNbxvn';

CREATE DATABASE og_tss WITH OWNER = tssowner;