DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA public AUTHORIZATION tssowner;
GRANT ALL ON SCHEMA public TO tssowner;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM public;
GRANT USAGE ON SCHEMA public TO public;
COMMENT ON SCHEMA PUBLIC IS 'og_timeseries storage';