/**
 * Copyright (C) 2009 - 2010 by OpenGamma Inc.
 * 
 * Please see distribution for license.
 */
package com.opengamma.financial.security;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.time.Instant;
import javax.time.InstantProvider;

import org.apache.commons.lang.Validate;
import org.fudgemsg.FudgeField;
import org.fudgemsg.FudgeFieldContainer;
import org.fudgemsg.MutableFudgeFieldContainer;
import org.fudgemsg.mapping.FudgeDeserializationContext;
import org.fudgemsg.mapping.FudgeSerializationContext;
import org.fudgemsg.types.StringFieldType;
import org.joda.beans.BeanDefinition;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.BasicMetaBean;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectMetaProperty;

import com.opengamma.engine.security.Security;
import com.opengamma.id.UniqueIdentifiable;
import com.opengamma.id.UniqueIdentifier;

/**
 * A document used to pass into and out of the security master.
 */
@BeanDefinition
public class SecurityDocument extends DirectBean implements UniqueIdentifiable {

  /**
   * The security unique identifier.
   */
  @PropertyDefinition
  private UniqueIdentifier _uniqueIdentifier;
  /**
   * The instant that the security is valid from.
   */
  @PropertyDefinition
  private Instant _validFromInstant;
  /**
   * The instant that the security is valid to.
   */
  @PropertyDefinition
  private Instant _validToInstant;
  /**
   * The instant that the security was last modified.
   */
  @PropertyDefinition
  private Instant _lastModifiedInstant;
  /**
   * The security.
   */
  @PropertyDefinition
  private Security _security;

  /**
   * Creates an instance.
   */
  public SecurityDocument() {
  }

  /**
   * Creates an instance.
   * @param security  the security, not null
   */
  public SecurityDocument(final Security security) {
    Validate.notNull(security, "Security must not be null");
    setUniqueIdentifier(security.getUniqueIdentifier());
    setSecurity(security);
  }

  // Temporary measure; these documents would be simpler written as proto definitions
  public final FudgeFieldContainer toFudgeMsg(final FudgeSerializationContext context) {
    final MutableFudgeFieldContainer message = context.newMessage();
    FudgeSerializationContext.addClassHeader(message, SecurityDocument.class);
    if (_uniqueIdentifier != null) {
      message.add("uniqueIdentifier", _uniqueIdentifier.toFudgeMsg(context));
    }
    if (_validFromInstant != null) {
      message.add("validFromInstant", _validFromInstant);
    }
    if (_validToInstant != null) {
      message.add("validToInstant", _validToInstant);
    }
    if (_lastModifiedInstant != null) {
      message.add("lastModifiedInstant", _lastModifiedInstant);
    }
    if (_security != null) {
      final MutableFudgeFieldContainer submsg = context.objectToFudgeMsg(_security);
      Class<?> c = _security.getClass();
      while (Security.class.isAssignableFrom(c)) {
        submsg.add(null, 0, StringFieldType.INSTANCE, c.getName());
        c = c.getSuperclass();
      }
      message.add("security", submsg);
    }
    return message;
  }

  // Temporary measure; these documents would be simpler written as proto definitions
  public static SecurityDocument fromFudgeMsg(final FudgeDeserializationContext context, final FudgeFieldContainer message) {
    final SecurityDocument result = new SecurityDocument();
    FudgeField field;
    field = message.getByName("uniqueIdentifier");
    if (field != null) {
      result.setUniqueIdentifier(UniqueIdentifier.fromFudgeMsg(message.getFieldValue(FudgeFieldContainer.class, field)));
    }
    field = message.getByName("validFromInstant");
    if (field != null) {
      result.setValidFromInstant(message.getFieldValue(InstantProvider.class, field).toInstant());
    }
    field = message.getByName("validToInstant");
    if (field != null) {
      result.setValidToInstant(message.getFieldValue(InstantProvider.class, field).toInstant());
    }
    field = message.getByName("lastModifiedInstant");
    if (field != null) {
      result.setLastModifiedInstant(message.getFieldValue(InstantProvider.class, field).toInstant());
    }
    field = message.getByName("security");
    if (field != null) {
      result.setSecurity(context.fieldValueToObject(Security.class, field));
    }
    return result;
  }

  // ------------------------- AUTOGENERATED START -------------------------
  /**
   * The meta-bean for {@code SecurityDocument}.
   * @return the meta-bean, not null
   */
  public static SecurityDocument.Meta meta() {
    return SecurityDocument.Meta.INSTANCE;
  }

  @Override
  public SecurityDocument.Meta metaBean() {
    return SecurityDocument.Meta.INSTANCE;
  }

  @Override
  protected Object propertyGet(String propertyName) {
    switch (propertyName.hashCode()) {
      case -125484198: // uniqueIdentifier
        return getUniqueIdentifier();
      case -3992261: // validFromInstant
        return getValidFromInstant();
      case -1035122102: // validToInstant
        return getValidToInstant();
      case 1792974178: // lastModifiedInstant
        return getLastModifiedInstant();
      case 949122880: // security
        return getSecurity();
    }
    return super.propertyGet(propertyName);
  }

  @Override
  protected void propertySet(String propertyName, Object newValue) {
    switch (propertyName.hashCode()) {
      case -125484198: // uniqueIdentifier
        setUniqueIdentifier((UniqueIdentifier) newValue);
        return;
      case -3992261: // validFromInstant
        setValidFromInstant((Instant) newValue);
        return;
      case -1035122102: // validToInstant
        setValidToInstant((Instant) newValue);
        return;
      case 1792974178: // lastModifiedInstant
        setLastModifiedInstant((Instant) newValue);
        return;
      case 949122880: // security
        setSecurity((Security) newValue);
        return;
    }
    super.propertySet(propertyName, newValue);
  }

  // -----------------------------------------------------------------------
  /**
   * Gets the security unique identifier.
   * @return the value of the property
   */
  public UniqueIdentifier getUniqueIdentifier() {
    return _uniqueIdentifier;
  }

  /**
   * Sets the security unique identifier.
   * @param uniqueIdentifier  the new value of the property
   */
  public void setUniqueIdentifier(UniqueIdentifier uniqueIdentifier) {
    this._uniqueIdentifier = uniqueIdentifier;
  }

  /**
   * Gets the the {@code uniqueIdentifier} property.
   * @return the property, not null
   */
  public final Property<UniqueIdentifier> uniqueIdentifier() {
    return metaBean().uniqueIdentifier().createProperty(this);
  }

  // -----------------------------------------------------------------------
  /**
   * Gets the instant that the security is valid from.
   * @return the value of the property
   */
  public Instant getValidFromInstant() {
    return _validFromInstant;
  }

  /**
   * Sets the instant that the security is valid from.
   * @param validFromInstant  the new value of the property
   */
  public void setValidFromInstant(Instant validFromInstant) {
    this._validFromInstant = validFromInstant;
  }

  /**
   * Gets the the {@code validFromInstant} property.
   * @return the property, not null
   */
  public final Property<Instant> validFromInstant() {
    return metaBean().validFromInstant().createProperty(this);
  }

  // -----------------------------------------------------------------------
  /**
   * Gets the instant that the security is valid to.
   * @return the value of the property
   */
  public Instant getValidToInstant() {
    return _validToInstant;
  }

  /**
   * Sets the instant that the security is valid to.
   * @param validToInstant  the new value of the property
   */
  public void setValidToInstant(Instant validToInstant) {
    this._validToInstant = validToInstant;
  }

  /**
   * Gets the the {@code validToInstant} property.
   * @return the property, not null
   */
  public final Property<Instant> validToInstant() {
    return metaBean().validToInstant().createProperty(this);
  }

  // -----------------------------------------------------------------------
  /**
   * Gets the instant that the security was last modified.
   * @return the value of the property
   */
  public Instant getLastModifiedInstant() {
    return _lastModifiedInstant;
  }

  /**
   * Sets the instant that the security was last modified.
   * @param lastModifiedInstant  the new value of the property
   */
  public void setLastModifiedInstant(Instant lastModifiedInstant) {
    this._lastModifiedInstant = lastModifiedInstant;
  }

  /**
   * Gets the the {@code lastModifiedInstant} property.
   * @return the property, not null
   */
  public final Property<Instant> lastModifiedInstant() {
    return metaBean().lastModifiedInstant().createProperty(this);
  }

  // -----------------------------------------------------------------------
  /**
   * Gets the security.
   * @return the value of the property
   */
  public Security getSecurity() {
    return _security;
  }

  /**
   * Sets the security.
   * @param security  the new value of the property
   */
  public void setSecurity(Security security) {
    this._security = security;
  }

  /**
   * Gets the the {@code security} property.
   * @return the property, not null
   */
  public final Property<Security> security() {
    return metaBean().security().createProperty(this);
  }

  // -----------------------------------------------------------------------
  /**
   * The meta-bean for {@code SecurityDocument}.
   */
  public static class Meta extends BasicMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code uniqueIdentifier} property.
     */
    private final MetaProperty<UniqueIdentifier> _uniqueIdentifier = DirectMetaProperty.ofReadWrite(this, "uniqueIdentifier", UniqueIdentifier.class);
    /**
     * The meta-property for the {@code validFromInstant} property.
     */
    private final MetaProperty<Instant> _validFromInstant = DirectMetaProperty.ofReadWrite(this, "validFromInstant", Instant.class);
    /**
     * The meta-property for the {@code validToInstant} property.
     */
    private final MetaProperty<Instant> _validToInstant = DirectMetaProperty.ofReadWrite(this, "validToInstant", Instant.class);
    /**
     * The meta-property for the {@code lastModifiedInstant} property.
     */
    private final MetaProperty<Instant> _lastModifiedInstant = DirectMetaProperty.ofReadWrite(this, "lastModifiedInstant", Instant.class);
    /**
     * The meta-property for the {@code security} property.
     */
    private final MetaProperty<Security> _security = DirectMetaProperty.ofReadWrite(this, "security", Security.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<Object>> _map;

    @SuppressWarnings("unchecked")
    protected Meta() {
      LinkedHashMap temp = new LinkedHashMap();
      temp.put("uniqueIdentifier", _uniqueIdentifier);
      temp.put("validFromInstant", _validFromInstant);
      temp.put("validToInstant", _validToInstant);
      temp.put("lastModifiedInstant", _lastModifiedInstant);
      temp.put("security", _security);
      _map = Collections.unmodifiableMap(temp);
    }

    @Override
    public SecurityDocument createBean() {
      return new SecurityDocument();
    }

    @Override
    public Class<? extends SecurityDocument> beanType() {
      return SecurityDocument.class;
    }

    @Override
    public Map<String, MetaProperty<Object>> metaPropertyMap() {
      return _map;
    }

    // -----------------------------------------------------------------------
    /**
     * The meta-property for the {@code uniqueIdentifier} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<UniqueIdentifier> uniqueIdentifier() {
      return _uniqueIdentifier;
    }

    /**
     * The meta-property for the {@code validFromInstant} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Instant> validFromInstant() {
      return _validFromInstant;
    }

    /**
     * The meta-property for the {@code validToInstant} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Instant> validToInstant() {
      return _validToInstant;
    }

    /**
     * The meta-property for the {@code lastModifiedInstant} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Instant> lastModifiedInstant() {
      return _lastModifiedInstant;
    }

    /**
     * The meta-property for the {@code security} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Security> security() {
      return _security;
    }

  }

  // -------------------------- AUTOGENERATED END --------------------------
}
